### ISSUE TITLE
`Protocol` concurrency issue

### ISSUE THREAD

**Issue by kim** [oscoin/oscoin#446] opened 2019-04-01 09:41 UTC
_Some_ incantation of running multiple nodes (locally) can lead to one node terminating with the following error:

`SQLite3 returned ErrorError while attempting to perform step: cannot start a transaction within a transaction`

**Comment by adinapoli-mndc** [comment] 2019-04-01 09:46
Assigning this to me (unless somebody wants it!) and taking a look after we merge Kim's work on the "unified peer discovery", which should hopefully make this more consistently reproducible.

**Comment by adinapoli-mndc** [comment] 2019-04-01 11:15
A possible permutation which triggers it non-deterministically and very rarely (procfile):

```
node1: stack exec oscoin -- --network devnet --ekg-port 8001  --api-port 8002  --gossip-port 7000 --seed 127.0.0.1:7001 --blockstore procfiles/run/store1.db
node2: stack exec oscoin -- --network devnet --ekg-port 9001  --api-port 9002  --gossip-port 7001 --seed 127.0.0.1:7000 --blockstore procfiles/run/store2.db
node3: stack exec oscoin -- --network devnet --ekg-port 10001 --api-port 10002 --gossip-port 7002 --seed 127.0.0.1:7000 --blockstore procfiles/run/store3.db
```

_Note_: It seems that in order to reproduce it, one has to first delete all the `store*.db` files and start fresh. If a failure happens, it happens at the very beginning.

**Comment by adinapoli-mndc** [comment] 2019-04-02 07:37
Initial report on this (very preliminary): it's interesting to note how the `ErrorError` type exists _only_ in the [direct-sqlite](https://github.com/IreneKnapp/direct-sqlite/blob/8e3da41c46b5de19942cc7bf421c3deb5117ba7a/Database/SQLite3/Bindings/Types.hsc#L69) library , which means this is being triggered by the `direct-sqlite` library. We use this library only in two places within `oscoin`, namely [here](https://github.com/oscoin/oscoin/blob/fa45bab26a7de4249f766f19dc91cd6349b1cfee/src/Oscoin/Storage/Block/SQLite/Internal.hs#L79) and [here](https://github.com/oscoin/oscoin/blob/fa45bab26a7de4249f766f19dc91cd6349b1cfee/src/Oscoin/Storage/Block/SQLite/Internal.hs#L98).

I have also thrown `dtruss` at it, and what it shows it's interesting:

```
node1 | 69346/0xf9a59:  pwrite(0x12, "\0", 0x200, 0x0)		 = 512 0
node1 | 69346/0xf9a59:  pwrite(0x12, "\0", 0x4, 0x200)		 = 4 0
node1 | 69346/0xf9a59:  pwrite(0x12, "\n\0", 0x1000, 0x204)		 = 4096 0
node1 | 69346/0xf9a59:  pwrite(0x12, "\t&\375*\0", 0x4, 0x1204)		 = 4 0
node1 | 69346/0xf9a59:  pwrite(0x12, "\0", 0x4, 0x1208)		 = 4 0
node1 | 69346/0xf9a59:  pwrite(0x12, "\n\0", 0x1000, 0x120C)		 = 4096 0
node1 | 69346/0xf9a59:  pwrite(0x12, "\t'\0", 0x4, 0x220C)		 = 4 0
node1 | 69346/0xf9a59:  pwrite(0x12, "\0", 0x4, 0x2210)		 = 4 0
node1 | 69346/0xf9a59:  pwrite(0x12, "\n\0", 0x1000, 0x2214)		 = 4096 0
node1 | 69346/0xf9a59:  pwrite(0x12, "\t&\375\234\0", 0x4, 0x3214)		 = 4 0
node1 | 69346/0xf9a59:  pwrite(0x12, "\0", 0x4, 0x3218)		 = 4 0
node1 | 69346/0xf9a59:  pwrite(0x12, "\r\0", 0x1000, 0x321C)		 = 4096 0
node1 | 69346/0xf9a59:  pwrite(0x12, "\t&\3776E8rWUQi8vGNi2Drjgb4FtifQz3pNjpYitXQVQXvVG3WBeub54JJnq438GFasNF2DrjgbKMipUawEnyGjevAghNzCyEQ1CkeSDMfNoGKaarZhMdqx\025\221_\3346m\3128!\0", 0x4, 0x421C)		 = 4 0
node1 | 69346/0xf9a59:  fcntl(0xC, 0x8, 0x7000033778A0)		 = 0 0
node1 | 69346/0xf9a59:  fcntl(0xC, 0x8, 0x7000033778A0)		 = 0 0
node1 | 69346/0xf9a59:  pwrite(0x12, "\0", 0x4, 0x4220)		 = 4 0
node1 | 69346/0xf9a59:  pwrite(0x12, "SQLite format 3\0", 0x1000, 0x4224)		 = 4096 0
node1 | 69346/0xf9a59:  pwrite(0x12, "\t&\373`\0", 0x4, 0x5224)		 = 4 0
node1 | 69346/0xf9a59:  pread(0x12, "0x7\003\0", 0x8, 0x5400)		 = 0 0
node1 | 69346/0xf9a58:  __semwait_signal(0x903, 0x0, 0x1)		 = -1 Err#60
node1 | 69346/0xf9a59:  fsync(0x12, 0x0, 0x0)		 = 0 0
node1 | 69346/0xf9a59:  open("/Users/adinapoli/oscoin/procfiles/run\0", 0x1000000, 0x1A4)		 = 19 0
node1 | 69346/0xf9a59:  fsync(0x13, 0x0, 0x0)		 = 0 0
node1 | 69346/0xf9a59:  close(0x13)		 = 0 0
node1 | 69346/0xf9a59:  pwrite(0x12, "\331\325\005\371 \241c\327\0", 0xC, 0x0)		 = 12 0
node1 | 69346/0xf9a59:  fsync(0x12, 0x0, 0x0)		 = 0 0
node1 | 69346/0xf9a59:  pwrite(0xC, "SQLite format 3\0", 0x1000, 0x0)		 = 4096 0
node1 | 69346/0xf9a59:  pwrite(0xC, "\n\0", 0x1000, 0x4000)		 = 4096 0
node1 | 69346/0xf9a59:  pwrite(0xC, "\n\0", 0x1000, 0xE000)		 = 4096 0
node1 | 69346/0xf9a59:  pwrite(0xC, "\n\0", 0x1000, 0x19000)		 = 4096 0
node1 | 69346/0xf9a59:  pwrite(0xC, "\r\0", 0x1000, 0x1B000)		 = 4096 0
node1 | 69346/0xf9a59:  fsync(0xC, 0x0, 0x0)		 = 0 0
node1 | 69346/0xf9a59:  close(0x12)		 = 0 0
node1 | 69346/0xf9a59:  unlink("/Users/adinapoli/oscoin/procfiles/run/store1.db-journal\0", 0x0, 0x0)		 = 0 0
```

Now, here is something very interesting: there are 2 calls to `pwrite(0x12, "SQLite format 3\0", 0x1000, 0x4224)`, the first which fails as the DB is locked (by somebody else writing into it), as you can witness from the next `__semwait_signal(0x903, 0x0, 0x1)` call. In case you are wondering `SQLite format 3\0` is the header of a new database, as you can see [here](https://github.com/mackyle/sqlite/blob/master/src/btree.c#L3276-L3291): the `zMagicHeader` array is aliased to [SQLITE_FILE_HEADER](https://github.com/mackyle/sqlite/blob/master/src/btree.c#L22), which is indeed `SQLite Format 3`. 

But this is iffy: if you look at a couple of lines above, there is a `pwrite(0x12, "\t&\3776E8rWUQi8vGNi2Drjgb4FtifQz3pNjpYitXQVQXvVG3WBeub54JJnq438GFasNF2DrjgbKMipUawEnyGjevAghNzCyEQ1CkeSDMfNoGKaarZhMdqx\025\221_\3346m\3128!\0", 0x4, 0x421C)`, which is
most likely trying to write the genesis block on disk: observe how `2DrjgbKMipUawEnyGjevAghNzCyEQ1CkeSDMfNoGKaarZhMdqx` is the genesis state hash!

To recap, something suspicious is going on here: we have two competing agents trying to both acquire the DB, but the calls to "please create a new DB" seems to happen after the call to write the genesis block on disk (mind, this could be the `dtruss` output not being perfectly ordered due to buffering issues).

If we check the code, we have this inside `SQLite.Internal`:

```haskell
initialize gen h@Handle{hConn} =
    getDataFileName "data/blockstore.sql" >>=
        readFile >>= \schema -> do
          Sql3.exec (Sql.connectionHandle hConn) schema -- this does the pwrite(new_database_header)
          unlessM (isStored hConn (blockHash gen)) $
              storeBlock' h gen -- This does the pwrite(genesis_block)
          pure h
```

A tentative speculation might be that due to the interaction between these two libraries, the first `Sql3.exec` is not executed immediately (as control is handed over the C FFI) whereas the second `storeBlock'` also tries to acquire the DB and start a transaction, so that when the first `exec` "wakes up", we are already inside a transaction and this fails (very wild speculation).

Probably using just one library might be a better idea anyway, so I will keep investigating.

**Comment by kim** [comment] 2019-04-02 07:48
Oh wait, try slap a mutex around the connection handle.

https://github.com/oscoin/oscoin/issues/298

**Comment by adinapoli-mndc** [comment] 2019-04-02 07:49
Uhm, that _could_ explain things. Provocative thought: do _we need_ 2 SQLite libraries? Would use just `sqlite-simple` have prevented this or are we flogging a dead horse?

**Comment by kim** [comment] 2019-04-02 07:53
`sqlite-simple` is implemented on top of `direct-sqlite`. I forget why @cloudhead  imported `direct-sqlite` directly (heh), some type not being re-exported I think.

The real issue is that it totally depends on what `sqlite-simple` thinks are good compile-time options for `sqlite`. Or we force everyone to use nix, so we all have the proper `libsqlite`, mwwwuaaaaahaa

**Comment by adinapoli-mndc** [comment] 2019-04-02 07:55
Oh, I see -- it just strikes me as odd that we are mixing and matching two different libs (albeit they are, effectively, the same one as one is a superset of the other).

Piggybacking from the linked issue ( #298): I suppose we could totally try forking & patching the library, and maintain our own fork up until the maintainer get back to us. Would that be a viable option? 

> Or we force everyone to use nix, so we all have the proper libsqlite, mwwwuaaaaahaa

Right 😂

**Comment by adinapoli-mndc** [comment] 2019-04-02 08:41
My day just got 1000 times better 😅 I have tried using the `systemlib` flag in `direct-sqlite` in order to use Darwin's stock `sqlite`, which seems to have the right flags (perhaps even too much of them):

```
> import Database.SQLite.Simple as SQL
> conn <- SQL.open "/tmp/test.sqlite3"
> query_ conn "PRAGMA compile_options;" :: IO [(Only String)]
[Only {fromOnly = "BUG_COMPATIBLE_20160819"},Only {fromOnly = "COMPILER=clang-10.0.0"},Only {fromOnly = "DEFAULT_CACHE_SIZE=2000"},Only {fromOnly = "DEFAULT_CKPTFULLFSYNC"},Only {fromOnly = "DEFAULT_JOURNAL_SIZE_LIMIT=32768"},Only {fromOnly = "DEFAULT_PAGE_SIZE=4096"},Only {fromOnly = "DEFAULT_SYNCHRONOUS=2"},Only {fromOnly = "DEFAULT_WAL_SYNCHRONOUS=1"},Only {fromOnly = "ENABLE_API_ARMOR"},Only {fromOnly = "ENABLE_COLUMN_METADATA"},Only {fromOnly = "ENABLE_DBSTAT_VTAB"},Only {fromOnly = "ENABLE_FTS3"},Only {fromOnly = "ENABLE_FTS3_PARENTHESIS"},Only {fromOnly = "ENABLE_FTS3_TOKENIZER"},Only {fromOnly = "ENABLE_FTS4"},Only {fromOnly = "ENABLE_FTS5"},Only {fromOnly = "ENABLE_JSON1"},Only {fromOnly = "ENABLE_LOCKING_STYLE=1"},Only {fromOnly = "ENABLE_PREUPDATE_HOOK"},Only {fromOnly = "ENABLE_RTREE"},Only {fromOnly = "ENABLE_SESSION"},Only {fromOnly = "ENABLE_SNAPSHOT"},Only {fromOnly = "ENABLE_SQLLOG"},Only {fromOnly = "ENABLE_UNKNOWN_SQL_FUNCTION"},Only {fromOnly = "ENABLE_UPDATE_DELETE_LIMIT"},Only {fromOnly = "HAS_CODEC_RESTRICTED"},Only {fromOnly = "HAVE_ISNAN"},Only {fromOnly = "MAX_LENGTH=2147483645"},Only {fromOnly = "MAX_MMAP_SIZE=1073741824"},Only {fromOnly = "MAX_VARIABLE_NUMBER=500000"},Only {fromOnly = "OMIT_AUTORESET"},Only {fromOnly = "OMIT_LOAD_EXTENSION"},Only {fromOnly = "STMTJRNL_SPILL=131072"},Only {fromOnly = "THREADSAFE=2"},Only {fromOnly = "USE_URI"}]
```

This is what I get now:

```
node3 | info  | mined block block_hash=2Drjgb8mDxvbmawCAyE5gSwgtoeEFWXAGTAcMRc3GQcya7ChJN ns="node" loc="Oscoin.Node:128:26"
node1 | procfiles/node1.sh: line 1: 50940 Segmentation fault: 11  cabal new-run oscoin -- --network devnet --ekg-port 8001 --api-port 8002 --gossip-port 7000 --seed 127.0.0.1:7001 --blockstore procfiles/run/store1.db
node1 | exit status 139
node2 | Interrupting...
node3 | Interrupting...
node3 | info  | broadcast block block_hash=2Drjgb8mDxvbmawCAyE5gSwgtoeEFWXAGTAcMRc3GQcya7ChJN ns="node" loc="Oscoin.Node:129:52"
node3 | error | Exception was thrown exception="user interrupt" callstack="CallStack (from HasCallStack):\n  logException, called at src/Oscoin/Telemetry/Logging.hs:312:63 in oscoin-0.1.0.0-inplace:Oscoin.Telemetry.Logging\n  withExceptionLogged, called at exe/node/Main.hs:142:11 in main:Main" loc="Main:142:11"
node2 | signal: interrupt
node3 | signal: interrupt
```

Ship it! :shipit: 

**NOTE:** Truth to be told Darwin ships with an ancient version of sqlite, and the `brew` formula is keg-only. Linking against the brewed version might be possible, but unfeasible past the experiment to see if that fixes the problem.

**Comment by cloudhead** [comment] 2019-04-02 10:13
If I remember, I had to import the `direct` module to enable foreign-key constraints via `Sql3.exec`

**Comment by adinapoli-mndc** [comment] 2019-04-02 10:25
Status update:

Using an uber-Otto-von-Bismarck-Schonhausen `MVar` lock makes the issue go away. The problem is that it's quite a deadly abstraction if misused (all the audience knows very well): sure enough I did get a deadlock in my first refactoring iteration, as we need to be careful which functions are top-level and need to be called while acquiring the lock and the ones which are second-class and needs to be called with the lock already taken.

Will try to polish what I have and send a PR.

I am _not sure_ if using a version of `SQLite` with `THREAD_SAFE=2` would have made some difference: sure enough the code segfaults with the stock Darwin's `sqlite` library, and pulling nix or patching the library seems to be not worth the effort.

Perhaps it's enough to use the MVar for now, and review this later if performance ends up being a concern.

**Closed** 2019-04-03 12:14 UTC
Labels: bug, storage
