### ISSUE TITLE
Fix external IP binding problems

### ISSUE THREAD

**Issue by geigerzaehler** [oscoin/oscoin#606] opened 2019-05-27 14:02 UTC
Please fill in @kim

**Comment by kim** [comment] 2019-05-29 16:30
Essentially the problem is this: on public clouds, instances usually only know about their network-private IPv4 address. If they have one or more public IPv4 addresses assigned to them, traffic just gets routed to that interface - applications on the instance can't bind to any of the external addresses.

Now, for membership and sync endpoint discovery to work over the public internet, the node needs to know about its external address(es), and use those for any identity/advertisement business, such that peers can actually connect back.

**Comment by kim** [comment] 2019-06-06 08:13
Following #626 we can close this for devnet. Running a public testnet will require the node to be able to distinguish between binding and external address - either by binding to the first interface available (`127.0.0.1` unless some flag is given), and using `--host` to advertise itself. Or by employing a proper NAT traversal scheme.

**Closed by kim** 2019-06-06 08:13 UTC
